### ISSUE TITLE
'error', 'Please reload Omegle to continue.'

### ISSUE THREAD

**Issue by Sancoraa** [Hafizur046/omegle-bot#1]
Hello, I have used your previous bot which worked well, however I can't understand how to use this one. I have ran index.js, then it just shows me a ">"

Also tried to go to `localhost:3000` but it just shows me a blank page with a text box. Thanks for any help !

**Comment by Hafizur046** [comment]
Hi, I'm surprised to see someone other than me using this project lol. This repo has been sitting for quite some time unmaintained and my last commit changed a few things regarding socket URI which caused the error in your case. I've made some commits that should resolve this issue.

**Comment by Sancoraa** [comment]
Thanks for the fast answer ! 
It seems that I still have an issue, perhaps I'm doing something wrong
When I do `!start` it seems like nothing happens. I don't know if it's supposed to print me stranger's answers or even my own message but if does, it doesn't work on my end :/

`!status` output is ` applicationEnabled: true interest: , enabled: false`

I also made some changes to the `Accept-Language` line 126 to match mine but it did not work before I did that, so that is most likely not where the issue come from.

**Comment by Sancoraa** [comment]
I still had your previous bot on my drive and managed to get it working again !
If the issue I have with this one comes from the script and not me being an idiot, don't worry about fixing it, at least if you don't have the need to. The old one's enough for me.

Thanks for taking your time answering me and actually update it tho, really appreciate it !

**Comment by Hafizur046** [comment]
It's being caused by the script itself, I didn't try using it in a long time, I'm not really sure what's broken. Would you mind telling me which commit your old  code is on. You can do that using the following command":
`git log`

**Comment by Sancoraa** [comment]
It's not from that repo, it's from an old one you have deleted, it wasn't even using react

**Comment by Hafizur046** [comment]
I've modified the repo name quite a while ago, It's the same repo

**Comment by Sancoraa** [comment]
Oh I see, thought you created a new one
Here's the latest commit, quite old ahah

```
commit 75b593f51e1099a25f22317161519dff34464101 (HEAD -> main, origin/main, origin/HEAD)
Author: Hafizur Rahman Fahim <hafijurrahman046@gmail.com>
Date:   Sat Oct 30 22:50:56 2021 +0600
```

**Comment by Hafizur046** [comment]
Okay, I'll take a look into this, although did you have to do any modification to the code to make it work or it just simply worked?

**Comment by Sancoraa** [comment]
I fixed it using [this comment](https://github.com/elias94/pyomegle/issues/18#issuecomment-1273822037), added the `2` on line 39 on the old commit

However after not more than 15 minutes it gets flagged as a bot and it needs the recaptcha, and going on the website I have to solve one on every discussion I get unfortunately. It resets maybe 3 hours after, which make it not quite worth it.

Do you know a way to implement proxies ? I tried using ProtonVPN but it seems like most of their servers are flagged :/
Note that I am on Linux, I don't know if proxies under NodeJS works the same as on Windows

**Comment by Hafizur046** [comment]
It seems like this comment fixes the issue but as you mentioned the captcha is still there, using proxies might be a solution, there are free proxy lists available out there, I might try using them which should in theory work. And as far as I know, HTTP proxies work pretty much the same way regardless of the system or environment

**Comment by Sancoraa** [comment]
I tried with free proxies yesterday but unfortunately I was still getting captchas. Maybe proxies were bad or I was doing something wrong. Nonetheless if I ever make it work I'll look for a way to automate it into the script, shouldn't be that hard in theory

**Comment by Hafizur046** [comment]
One small thing to note is that Nodjes (node-fetch to be specific) does not use system proxy by default as far as I know. Besides, Omegle probably has some fingerprinting mechanism. The application in its current state has a pretty unique fingerprint, changing the User-Agent in the header to something that can blend in. A few other things should make the fingerprint a lot less unique, but to sum it all up, it is all just an assumption, it's possible that just properly configuring proxies will solve the issue.

**Comment by Sancoraa** [comment]
Just using a http-proxy did not help yesterday, going on the website with Firefox was still triggering captchas. I'll try later to change the User-Agent
I'll also delete cookies/cache to see if this can help. I'll let you know if I find something useful

**Comment by Sancoraa** [comment]
I have changed the User-Agent but it sadly did not fix anything.
I downloaded the `https-proxy-agent` package and imported it.
I then made a few modifications to the `requestOptions`, but I can't get an answer from the server after doing so.
Tried approx. 10 free proxies

```js
import HttpsProxyAgent from "https-proxy-agent";

const proxyAgent = new HttpsProxyAgent('51.159.115.233:3128');

var requestOptions = {
  method: "POST",
  headers: myHeaders,
  redirect: "follow",
  agent: proxyAgent,
};
```

**Comment by Hafizur046** [comment]
It's strange for some random proxy to be shadow banned on Omegle, could you try using the proxy in the browser and see if you can open Omegle through it?

**Comment by Sancoraa** [comment]
Hmm, just tried with differents https proxies from different website, never succeeded to connect. Sometimes I get "Error connecting to server", sometimes it tries to connect for 30~ secondes then "Banned."

I think most of the free proxies are flagged, maybe it would work with paid proxies

**Comment by Hafizur046** [comment]
I've a different feeling about this. Omegle is probably able to detect the proxy somehow, I can confirm this by creating a proxy of my own and see if it gets similar response from omegle.

**Comment by Sancoraa** [comment]
I just tried with free web proxies like [this one](https://www.proxysite.com/) and I have the same result. If proxies are indeed detected I think the only solution is to have a captcha solver

**Comment by Hafizur046** [comment]
I guess a captcha solver can solve the issue but I've never used one and I'm almost completely unaware of what they're capable of and how to use one. If you can then you're more than welcome to open a PR integrating some captcha resolver.

**Comment by Hafizur046** [comment]
Apart from these, we've actually gone quite off-topic with this issue, even though it's not any serious project, I think a tiny bit of organization wouldn't be hurting anyone. Therefore, I'll be closing this issue and I'm suggesting you to create a new issue with the title "bypass captcha using captcha-resolver/proxy" if you would like to discuss this further.
